#!/usr/bin/env python3
from __future__ import annotations
import json,re
from pathlib import Path
R=Path(__file__).resolve().parents[3]
NEXT=("Continue canonical Tamil first-pass transcription with PDF 65–69, preserving source order, stable page anchors and page-level historical-glyph checks. Keep all first-pass pages draft/needs-review. Do not begin English translation until the Tamil canonical layer passes the separate visual-fidelity and final historical-glyph verification gates.")
changed=[]
def w(rel,s):
 p=R/rel; old=p.read_text(encoding='utf-8') if p.exists() else ''
 if old!=s: p.write_text(s,encoding='utf-8'); changed.append(rel)
def sec(s,a,b,new):
 i=s.find(a)
 if i<0:return s
 j=s.find(b,i+len(a)) if b else len(s)
 if j<0:return s
 return s[:i]+new.rstrip()+"\n\n"+s[j:]
# guard source batches
for rel,need in {
 'works/naam/transcription/parts/pdf-055-059.md':['<!-- source: pdf=55','<!-- source: pdf=59'],
 'works/naam/transcription/parts/pdf-060-064.md':['<!-- source: pdf=60','<!-- source: pdf=64','## பின்னணிப் பாடல்']}.items():
 t=(R/rel).read_text(encoding='utf-8')
 for x in need:
  if x not in t: raise SystemExit(f'missing {x} in {rel}')
# index
p='works/naam/transcription/index.json'; d=json.loads((R/p).read_text(encoding='utf-8'))
d.update(status='partial-first-pass',first_pass_complete=False,first_pass_pages_completed=60,first_pass_pdf_range_completed=[5,64],draft_pages=60,verified_pages=0,visual_fidelity_passed_pages=0,historical_glyph_checked_pages=60,historical_glyph_verified_pages=0,review_pages=60,open_uncertainty_markers=2,current_through_pdf=64,current_through_printed_page=64,next_batch_pdf_range=[65,69],next_action=NEXT)
parts=d.setdefault('parts',[])
for path,rng in [('parts/pdf-055-059.md',[55,59]),('parts/pdf-060-064.md',[60,64])]:
 if not any(x.get('path')==path for x in parts): parts.append({'path':path,'pdf_range':rng,'printed_range':rng,'status':'draft-needs-review','historical_glyph_status':'checked-first-pass','open_uncertainties':0})
parts.sort(key=lambda x:x['pdf_range'][0]); w(p,json.dumps(d,ensure_ascii=False,indent=2)+'\n')
# metadata
p='works/naam/metadata.yaml'; t=(R/p).read_text(encoding='utf-8')
for a,b in [('first_pass_pages_completed: 50','first_pass_pages_completed: 60'),('first_pass_pdf_range_completed: "5-54"','first_pass_pdf_range_completed: "5-64"'),('first_pass_current_through_pdf: 54','first_pass_current_through_pdf: 64'),('first_pass_current_through_printed_page: 54','first_pass_current_through_printed_page: 64'),('draft_pages: 50','draft_pages: 60'),('review_pages: 50','review_pages: 60'),('current_batch_path: "transcription/parts/pdf-050-054.md"','current_batch_path: "transcription/parts/pdf-060-064.md"'),('current_textual_notes_path: "notes/textual-notes-pdf-050-054.md"','current_textual_notes_path: "notes/textual-notes-pdf-060-064.md"'),('pages_checked: 50','pages_checked: 60'),('canonical_tamil_transcription: partial-first-pass-through-pdf-054','canonical_tamil_transcription: partial-first-pass-through-pdf-064'),('historical_glyph_audit: partial-first-pass-through-pdf-054','historical_glyph_audit: partial-first-pass-through-pdf-064')]: t=t.replace(a,b)
anchor='    - "transcription/parts/pdf-050-054.md"\n'
if 'pdf-055-059.md' not in t:t=t.replace(anchor,anchor+'    - "transcription/parts/pdf-055-059.md"\n    - "transcription/parts/pdf-060-064.md"\n',1)
t=re.sub(r'next_action: ".*?"\s*$',f'next_action: "{NEXT}"',t,count=1,flags=re.S); w(p,t)
# work README
p='works/naam/README.md'; t=(R/p).read_text(encoding='utf-8')
for a,b in [('PDF 5–54 / 50 of 67 pages','PDF 5–64 / 60 of 67 pages'),('50 pages checked / 0 final-verified','60 pages checked / 0 final-verified'),('Current textual notes: `notes/textual-notes-pdf-050-054.md`','Current textual notes: `notes/textual-notes-pdf-060-064.md`'),('PDF **5–54** has now been transcribed as source-order draft material in ten five-page batches.','PDF **5–64** has now been transcribed as source-order draft material in twelve five-page batches.'),('PDF 10–54 adds **0** new uncertainty markers','PDF 10–64 adds **0** new uncertainty markers'),('**0** of the fifty first-pass pages are called verified yet.','**0** of the sixty first-pass pages are called verified yet.')]:t=t.replace(a,b)
if 'transcription/parts/pdf-060-064.md' not in t:t=t.replace('`transcription/parts/pdf-050-054.md`  ','`transcription/parts/pdf-050-054.md`, `transcription/parts/pdf-055-059.md`, `transcription/parts/pdf-060-064.md`  ',1)
t=re.sub(r'## Exact next activity\n\n\*\*.*?\*\*\s*$',f'## Exact next activity\n\n**{NEXT}**\n',t,count=1,flags=re.S);w(p,t)
# transcription README
p='works/naam/transcription/README.md';t=(R/p).read_text(encoding='utf-8')
for a,b in [('PDF 5–54 / 50 pages','PDF 5–64 / 60 pages'),('historical-glyph pages checked during first pass: **50/67**','historical-glyph pages checked during first pass: **60/67**'),('current batch: `parts/pdf-050-054.md`','current batch: `parts/pdf-060-064.md`'),('PDF 6–54: visible printed numerals 6–54','PDF 6–64: visible printed numerals 6–64'),('PDF 10–54 introduced **0 new explicit uncertainty markers**.','PDF 10–64 introduced **0 new explicit uncertainty markers**.')]:t=t.replace(a,b)
t=re.sub(r'## Next activity\n\n\*\*.*?\*\*\s*$',f'## Next activity\n\n**{NEXT}**\n',t,count=1,flags=re.S);w(p,t)
# glyph audit coverage + findings
p='works/naam/notes/historical-glyph-audit.md';t=(R/p).read_text(encoding='utf-8')
t=t.replace('| PDF 50–54 | 5 | 5 | 0 | 5 | partial-first-pass |\n| PDF 55–71 | 17 | 0 | 0 | 0 | not-started |\n| **Total** | **67** | **50** | **0** | **50** | **partial-first-pass** |','| PDF 50–54 | 5 | 5 | 0 | 5 | partial-first-pass |\n| PDF 55–59 | 5 | 5 | 0 | 5 | partial-first-pass |\n| PDF 60–64 | 5 | 5 | 0 | 5 | partial-first-pass |\n| PDF 65–71 | 7 | 0 | 0 | 0 | not-started |\n| **Total** | **67** | **60** | **0** | **60** | **partial-first-pass** |')
if '| 64 | 64 | historical `னா` cluster | `வாடினான்`' not in t:
 rows='''| 55 | 55 | historical `லை` cluster | `உயிலை` | `லை` | enlarged source pixels | draft-supported |\n| 57 | 57 | historical `லை` name ending | `அண்ணுமலை` | `லை` | enlarged source pixels | draft-supported |\n| 59 | 59 | historical `றா` cluster | `தவறாமல்` | `றா` | enlarged source pixels | draft-supported |\n| 59 | 59 | historical `னை` cluster | `முனையிலே` | `னை` | enlarged source pixels | draft-supported |\n| 59 | 59 | historical `ணா` cluster | `அண்ணா` | `ணா` | enlarged source pixels + same-edition comparison | draft-supported |\n| 60 | 60 | historical `ணா` cluster | `அண்ணா` | `ணா` | enlarged source pixels | draft-supported |\n| 61 | 61 | historical `லை` name ending | `அண்ணுமலை` | `லை` | enlarged source pixels | draft-supported |\n| 62 | 62 | historical `லை` name ending | `அண்ணுமலை` | `லை` | enlarged source pixels | draft-supported |\n| 62 | 62 | historical `னை` cluster | `ஜமீனை` | `னை` | enlarged source pixels | draft-supported |\n| 64 | 64 | historical `னா` cluster | `வாடினான்` | `னா` | enlarged source pixels | draft-supported |\n'''
 marker='\nThese findings decode character identity only.';t=t.replace(marker,'\n'+rows+marker,1)
w(p,t)
# project handover
p='works/naam/PROJECT_HANDOVER.md';t=(R/p).read_text(encoding='utf-8')
for a,b in [('PDF 5–54 / 50 of 67 pages','PDF 5–64 / 60 of 67 pages'),('historical-glyph first-pass checked: **50/67**','historical-glyph first-pass checked: **60/67**')]:t=t.replace(a,b)
if '`transcription/parts/pdf-060-064.md`' not in t:t=t.replace('- `transcription/parts/pdf-050-054.md`;','- `transcription/parts/pdf-050-054.md`;\n- `transcription/parts/pdf-055-059.md`;\n- `transcription/parts/pdf-060-064.md`;',1)
if '`notes/textual-notes-pdf-060-064.md`' not in t:t=t.replace('- `notes/textual-notes-pdf-050-054.md`;','- `notes/textual-notes-pdf-050-054.md`;\n- `notes/textual-notes-pdf-055-059.md`;\n- `notes/textual-notes-pdf-060-064.md`;',1)
t=re.sub(r'## Exact next activity\n\n> \*\*.*?\*\*\s*$',f'## Exact next activity\n\n> **{NEXT}**\n',t,count=1,flags=re.S);w(p,t)
# next prompt overwrite
p='works/naam/NEXT_CHAT_PROMPT.md';w(p,f'''# Next Chat Prompt — நாம்\n\nContinue directly in `pugazg/kalaignar-cinema-works`, branch `main`, active work `works/naam/`.\n\n## LIVE MAIN IS AUTHORITATIVE\n\nFetch live `main` first and preserve newer durable work.\n\nCurrent durable checkpoint:\n\n- source intake / mapping: **complete / verified**;\n- canonical Tamil first pass: **PDF 5–64 / 60 of 67 pages**;\n- verified pages: **0**;\n- historical-glyph first-pass checked: **60/67**;\n- historical-glyph final verified: **0/67**;\n- open uncertainty markers: **2**;\n- next batch: **PDF 65–69**.\n\n## Controlling source\n\nResolve `TVA_BOK_0064201_நாம்.pdf` before source-level visual work. Recorded identity: **72 PDF pages**, **115,948,588 bytes**, SHA-256 `0f7a54882eb6a5a8f83b29060c771ef18dee2b9e108c8797184de2b97c30b7ad`, image-only; screenplay PDF **5–71**.\n\n## Frozen first-pass batches PDF 5–64\n\nDo not redo or silently rewrite completed pages absent new direct-scan evidence. The cumulative source uncertainties remain exactly **2** (PDF 5 damaged introductory text; PDF 9 unclear montage word). PDF 10–64 adds none.\n\nPDF 59–60 is a source-visible poetic/song-like witness between scenes 36 and 37; PDF 64 carries the explicit `பின்னணிப் பாடல்` marker. Preserve booklet text only and do not infer missing lyrics, title, tune or authorship.\n\nEnglish translation remains blocked until the canonical Tamil passes visual-fidelity and final historical-glyph verification.\n\n## Exact next activity\n\n> **{NEXT}**\n''')
# data works
p='data/works.json';d=json.loads((R/p).read_text(encoding='utf-8'));n=next(x for x in d if x.get('id')=='naam');n.update(canonical_tamil_transcription='partial-first-pass-through-pdf-064',historical_glyph_audit='partial-first-pass-through-pdf-064',next_action=NEXT,canonical_tamil_first_pass_pages_completed=60,canonical_tamil_first_pass_pdf_range_completed='5-64',canonical_tamil_first_pass_current_through_pdf=64,canonical_tamil_draft_pages=60,canonical_tamil_verified_pages=0,canonical_tamil_review_pages=60,canonical_tamil_open_uncertainty_markers=2,canonical_tamil_current_batch_path='works/naam/transcription/parts/pdf-060-064.md',historical_glyph_pages_checked=60,historical_glyph_pages_verified=0,visual_fidelity_audit='not-started',canonical_tamil_current_textual_notes_path='works/naam/notes/textual-notes-pdf-060-064.md');w(p,json.dumps(d,ensure_ascii=False,separators=(',',':'))+'\n')
# root README block
p='README.md';t=(R/p).read_text(encoding='utf-8');block=f'''## நாம் status\n\n`TVA_BOK_0064201_நாம்.pdf` is the **active cinema source**. Intake and the 45-scene structural map are complete; canonical Tamil first-pass transcription is in progress.\n\n- canonical Tamil first pass: **PDF 5–64 / 60 of 67 pages**;\n- verified pages: **0**; visual-fidelity audit: **not-started**;\n- historical-glyph first-pass checked: **60/67**; final glyph-verified: **0/67**;\n- open source uncertainty markers: **2**, both carried from PDF 5/9; PDF 10–64 adds none;\n- newest batch: `works/naam/transcription/parts/pdf-060-064.md`;\n- PDF 59–60 and PDF 64 performance/lyric witnesses remain booklet-only; no outside reconstruction/authorship inference;\n- downstream derivatives and English remain blocked pending verified Tamil.\n\n**Next:** {NEXT}\n''';t=sec(t,'## நாம் status','## ராஜா ராணி status',block);w(p,t)
# master handover active section
p='docs/HANDOVER_KALAIGNAR_CINEMA_WORKS.md';t=(R/p).read_text(encoding='utf-8');t=re.sub(r'- \*\*Naam / நாம்\*\* — active work;.*?Source SHA-256 `0f7a54882eb6a5a8f83b29060c771ef18dee2b9e108c8797184de2b97c30b7ad`\.', '- **Naam / நாம்** — active work; intake/map complete; canonical Tamil first pass **PDF 5–64 / 60 of 67**; glyph first-pass **60/67**; verified **0/67**; 2 carried source uncertainties; next PDF 65–69. Source SHA-256 `0f7a54882eb6a5a8f83b29060c771ef18dee2b9e108c8797184de2b97c30b7ad`.',t,count=1,flags=re.S)
block=f'''## 8. Naam active checkpoint\n\nWork: `works/naam/`  \nSource: `TVA_BOK_0064201_நாம்.pdf`\n\n- intake / whole-scan map: **complete / verified**;\n- canonical Tamil first pass: **PDF 5–64 / 60 of 67 pages**;\n- canonical verified pages: **0**; visual-fidelity audit: **not-started**;\n- historical-glyph first-pass checked / final verified: **60/67 / 0/67**;\n- open source uncertainties: **2**, both inherited from PDF 5/9;\n- current batch: `works/naam/transcription/parts/pdf-060-064.md`;\n- current source notes: `works/naam/notes/textual-notes-pdf-060-064.md`;\n- PDF 59–60 and PDF 64 performance/lyric witnesses remain source-only;\n- structured derivatives / English / reader remain blocked.\n\n**Exact next activity:** {NEXT}\n''';t=sec(t,'## 8. Naam active checkpoint','## 9. Ammayappan closed checkpoint',block);w(p,t)
# status audit
p='docs/STATUS_CONSISTENCY_AUDIT.md';t=(R/p).read_text(encoding='utf-8').replace('Audit date: 2026-09-06','Audit date: 2026-09-08');t=t.replace('first pass **PDF 5–54 / 50 of 67**, 0 verified','first pass **PDF 5–64 / 60 of 67**, 0 verified')
block=f'''## Naam current checkpoint\n\n- source intake / structural mapping: **complete / verified**;\n- canonical Tamil first pass: **PDF 5–64 / 60 of 67 pages**;\n- verified pages / visual-fidelity passed: **0 / 0**;\n- historical-glyph first-pass checked / final verified: **60 / 0**;\n- open uncertainty markers: **2**, both carried from PDF 5/9;\n- current draft: `works/naam/transcription/parts/pdf-060-064.md`;\n- current source notes: `works/naam/notes/textual-notes-pdf-060-064.md`;\n- PDF 55–64 introduces no new explicit uncertainty;\n- PDF 59–60 and PDF 64 preserve booklet-only performance/lyric evidence;\n- downstream scene/dialogue/character/song/English layers remain blocked until verified Tamil.\n\n**Next production phase:** {NEXT}\n''';t=sec(t,'## Naam current checkpoint','## Ammayappan current checkpoint',block);t=re.sub(r'\*\*Naam / நாம்\*\* is the active production work with intake/map complete and canonical Tamil first pass at \*\*PDF 5–54 / 50 of 67 pages\*\*, \*\*0 verified pages\*\*, historical-glyph first-pass \*\*50/67\*\*, and \*\*2 carried source uncertainties\*\*\. The next batch is PDF 55–59\.', '**Naam / நாம்** is the active production work with intake/map complete and canonical Tamil first pass at **PDF 5–64 / 60 of 67 pages**, **0 verified pages**, historical-glyph first-pass **60/67**, and **2 carried source uncertainties**. The next batch is PDF 65–69.',t,count=1);w(p,t)
print('Synchronized:');[print('-',x) for x in changed]
