#!/usr/bin/env python3
from __future__ import annotations
import json,re
from pathlib import Path
R=Path(__file__).resolve().parents[3]
NEXT=("Complete the canonical Tamil first pass with the final remainder PDF 70–71, beginning by continuing the same scene-45 Kumaran dialogue that ends PDF 69 at `படித்தால் பாவம் என்று உன்`. Preserve source order, stable page anchors and page-level historical-glyph checks. Keep both pages draft/needs-review. After PDF 71, synchronize and close the first-pass gate, then begin the separate visual-fidelity audit; English translation remains blocked until the Tamil canonical layer passes both visual-fidelity and final historical-glyph verification.")
changed=[]
def wr(rel,s):
 p=R/rel;o=p.read_text(encoding='utf-8') if p.exists() else ''
 if o!=s:p.write_text(s,encoding='utf-8');changed.append(rel)
def section(s,a,b,new):
 i=s.find(a);j=s.find(b,i+len(a)) if i>=0 else -1
 if i<0 or j<0:raise SystemExit(f'section missing: {a} / {b}')
 return s[:i]+new.rstrip()+'\n\n'+s[j:]
# Guards
ip=R/'works/naam/transcription/index.json';d=json.loads(ip.read_text(encoding='utf-8'))
for k,v in {'first_pass_pages_completed':60,'current_through_pdf':64,'historical_glyph_checked_pages':60,'verified_pages':0,'open_uncertainty_markers':2}.items():
 if d.get(k)!=v:raise SystemExit(f'index precondition {k}: {d.get(k)!r}')
if d.get('next_batch_pdf_range')!=[65,69]:raise SystemExit('expected next batch 65-69')
b=(R/'works/naam/transcription/parts/pdf-065-069.md').read_text(encoding='utf-8')
for x in ['<!-- source: pdf=65','<!-- source: pdf=69','## காட்சி 40','## காட்சி 41','## காட்சி 42','## காட்சி 43','## காட்சி-44','## காட்சி-45','படித்தால் பாவம் என்று உன்']:
 if x not in b:raise SystemExit(f'batch guard missing {x}')
# Index
d.update(status='partial-first-pass',first_pass_complete=False,first_pass_pages_completed=65,first_pass_pdf_range_completed=[5,69],draft_pages=65,verified_pages=0,visual_fidelity_passed_pages=0,historical_glyph_checked_pages=65,historical_glyph_verified_pages=0,review_pages=65,open_uncertainty_markers=2,current_through_pdf=69,current_through_printed_page=69,next_batch_pdf_range=[70,71],next_action=NEXT)
ps=d.setdefault('parts',[])
if not any(x.get('path')=='parts/pdf-065-069.md' for x in ps):ps.append({'path':'parts/pdf-065-069.md','pdf_range':[65,69],'printed_range':[65,69],'status':'draft-needs-review','historical_glyph_status':'checked-first-pass','open_uncertainties':0})
ps.sort(key=lambda x:x['pdf_range'][0]);wr('works/naam/transcription/index.json',json.dumps(d,ensure_ascii=False,indent=2)+'\n')
# Metadata
p='works/naam/metadata.yaml';s=(R/p).read_text(encoding='utf-8')
for a,z in [('first_pass_pages_completed: 60','first_pass_pages_completed: 65'),('first_pass_pdf_range_completed: "5-64"','first_pass_pdf_range_completed: "5-69"'),('first_pass_current_through_pdf: 64','first_pass_current_through_pdf: 69'),('first_pass_current_through_printed_page: 64','first_pass_current_through_printed_page: 69'),('draft_pages: 60','draft_pages: 65'),('review_pages: 60','review_pages: 65'),('current_batch_path: "transcription/parts/pdf-060-064.md"','current_batch_path: "transcription/parts/pdf-065-069.md"'),('current_textual_notes_path: "notes/textual-notes-pdf-060-064.md"','current_textual_notes_path: "notes/textual-notes-pdf-065-069.md"'),('pages_checked: 60','pages_checked: 65'),('canonical_tamil_transcription: partial-first-pass-through-pdf-064','canonical_tamil_transcription: partial-first-pass-through-pdf-069'),('historical_glyph_audit: partial-first-pass-through-pdf-064','historical_glyph_audit: partial-first-pass-through-pdf-069')]:s=s.replace(a,z)
a='    - "transcription/parts/pdf-060-064.md"\n'
if 'pdf-065-069.md' not in s:s=s.replace(a,a+'    - "transcription/parts/pdf-065-069.md"\n',1)
if 'batch_065_069_consequential_decodings:' not in s:
 m='mapped_source_visible_performance_structures:\n';x='''  batch_065_069_consequential_decodings:\n    - pdf_page: 65\n      source_supported_unicode: "மனிதனாகுகிறதும் / மனிதனாகுவதும்"\n      family: "னா"\n    - pdf_page: 65\n      source_supported_unicode: "அண்ணுமலை"\n      family: "லை"\n    - pdf_page: 66\n      source_supported_unicode: "காலணா / காலை"\n      family: "ணா / லை"\n    - pdf_page: 67\n      source_supported_unicode: "மனைவி"\n      family: "னை"\n    - pdf_page: 68\n      source_supported_unicode: "உயிலை"\n      family: "லை"\n    - pdf_page: 69\n      source_supported_unicode: "உன்னை"\n      family: "னை"\n\n''';s=s.replace(m,x+m,1)
if 'pdf_65_69_new_performance_structures' not in s:s=s.replace('  high_confidence_blocks: 6\n','  high_confidence_blocks: 6\n  pdf_65_69_new_performance_structures: 0\n',1)
s=re.sub(r'next_action: ".*?"\s*$',f'next_action: "{NEXT}"',s,count=1,flags=re.S);wr(p,s)
# Work README
p='works/naam/README.md';s=(R/p).read_text(encoding='utf-8')
for a,z in [('PDF 5–64 / 60 of 67 pages','PDF 5–69 / 65 of 67 pages'),('60 pages checked / 0 final-verified','65 pages checked / 0 final-verified'),('Current textual notes: `notes/textual-notes-pdf-060-064.md`','Current textual notes: `notes/textual-notes-pdf-065-069.md`'),('PDF 10–64 adds **0** new uncertainty markers','PDF 10–69 adds **0** new uncertainty markers'),('**0** of the sixty first-pass pages are called verified yet.','**0** of the sixty-five first-pass pages are called verified yet.')]:s=s.replace(a,z)
if '`transcription/parts/pdf-065-069.md`' not in s:s=s.replace('`transcription/parts/pdf-060-064.md`  ','`transcription/parts/pdf-060-064.md`, `transcription/parts/pdf-065-069.md`  ',1)
s=re.sub(r'PDF \*\*5–64\*\* has now been transcribed as source-order draft material in twelve five-page batches\.[^\n]*','PDF **5–69** has now been transcribed as source-order draft material in thirteen five-page batches. The newest batch contains `காட்சி 40–45` and ends mid-dialogue in `காட்சி-45` on PDF 69; PDF 70 continues the same Kumaran utterance.',s,count=1)
if 'PDF 65–69 `மனிதனாகுகிறதும்`' not in s:
 m='- PDF 50 completes the mapped scene-31 lyrical witness from the booklet only; PDF 52 opens `காட்சி-32`, and PDF 54 opens `காட்சி 33`;\n';x='- PDF 65–69 `மனிதனாகுகிறதும்` / `மனிதனாகுவதும்`, `காலணா`, `காலை`, `மனைவி`, `உயிலை`, and `உன்னை` were checked against occurrence-specific historical families;\n- PDF 65 opens `காட்சி 40` and `காட்சி 41`; PDF 67 opens `காட்சி 42` and `காட்சி 43`; PDF 68 opens `காட்சி-44` and `காட்சி-45`; PDF 69 ends mid-Kumaran dialogue and PDF 70 must continue the same utterance;\n- PDF 65–69 adds no new distinct song/lyric/performance structure and introduces **0 new explicit uncertainty markers**;\n';s=s.replace(m,m+x,1)
s=re.sub(r'## Exact next activity\n\n\*\*.*?\*\*\s*$',f'## Exact next activity\n\n**{NEXT}**\n',s,count=1,flags=re.S);wr(p,s)
# Transcription README
p='works/naam/transcription/README.md';s=(R/p).read_text(encoding='utf-8')
for a,z in [('PDF 5–64 / 60 pages','PDF 5–69 / 65 pages'),('historical-glyph pages checked during first pass: **60/67**','historical-glyph pages checked during first pass: **65/67**'),('current batch: `parts/pdf-060-064.md`','current batch: `parts/pdf-065-069.md`'),('PDF 6–64: visible printed numerals 6–64','PDF 6–69: visible printed numerals 6–69'),('PDF 10–64 introduced **0 new explicit uncertainty markers**.','PDF 10–69 introduced **0 new explicit uncertainty markers**.')]:s=s.replace(a,z)
if '## PDF 65–69 source decisions' not in s:
 x='''\n## PDF 65–69 source decisions\n\nThe thirteenth batch contains source scenes 40–45 and ends mid-dialogue in scene 45. PDF 65 checks `மனிதனாகுகிறதும்` / `மனிதனாகுவதும்` (`னா`) and `அண்ணுமலை` (`லை`); PDF 66 checks `காலணா` (`ணா`) and `காலை` (`லை`) and preserves `உன்மீனு`; PDF 67 checks `மனைவி` (`னை`); PDF 68 checks `உயிலை` (`லை`); PDF 69 checks `உன்னை` (`னை`) and ends at `படித்தால் பாவம் என்று உன்`. PDF 65–69 adds no new uncertainty marker or distinct performance structure. See `../notes/textual-notes-pdf-065-069.md`.\n'''
 s+=x
s=re.sub(r'## Next activity\n\n\*\*.*?\*\*\s*$',f'## Next activity\n\n**{NEXT}**\n',s,count=1,flags=re.S);wr(p,s)
# Glyph audit
p='works/naam/notes/historical-glyph-audit.md';s=(R/p).read_text(encoding='utf-8')
a='| PDF 60–64 | 5 | 5 | 0 | 5 | partial-first-pass |\n| PDF 65–71 | 7 | 0 | 0 | 0 | not-started |\n| **Total** | **67** | **60** | **0** | **60** | **partial-first-pass** |';z='| PDF 60–64 | 5 | 5 | 0 | 5 | partial-first-pass |\n| PDF 65–69 | 5 | 5 | 0 | 5 | partial-first-pass |\n| PDF 70–71 | 2 | 0 | 0 | 0 | not-started |\n| **Total** | **67** | **65** | **0** | **65** | **partial-first-pass** |'
if a not in s:raise SystemExit('glyph coverage precondition missing')
s=s.replace(a,z,1)
if '| 69 | 69 | historical `னை` cluster | `உன்னை`' not in s:
 rows='''| 65 | 65 | historical `னா` clusters | `மனிதனாகுகிறதும்` / `மனிதனாகுவதும்` | `னா` | enlarged source pixels | draft-supported |\n| 65 | 65 | historical `லை` name ending | `அண்ணுமலை` | `லை` | enlarged source pixels | draft-supported |\n| 66 | 66 | historical `ணா` cluster | `காலணா` | `ணா` | enlarged source pixels | draft-supported |\n| 66 | 66 | historical `லை` cluster | `காலை` | `லை` | enlarged source pixels | draft-supported |\n| 67 | 67 | historical `னை` cluster | `மனைவி` | `னை` | enlarged source pixels | draft-supported |\n| 68 | 68 | historical `லை` cluster | `உயிலை` | `லை` | enlarged source pixels | draft-supported |\n| 69 | 69 | historical `னை` cluster | `உன்னை` | `னை` | enlarged source pixels | draft-supported |\n''';s=s.replace('\nThese findings decode character identity only.','\n'+rows+'\nThese findings decode character identity only.',1)
wr(p,s)
# Project handover
p='works/naam/PROJECT_HANDOVER.md';s=(R/p).read_text(encoding='utf-8').replace('PDF 5–64 / 60 of 67 pages','PDF 5–69 / 65 of 67 pages').replace('historical-glyph first-pass checked: **60/67**','historical-glyph first-pass checked: **65/67**')
i=s.find('Current canonical files:\n');j=s.find('\n## Source identity',i)
if i>=0 and j>i:
 files='''Current canonical files:\n\n- `transcription/index.json`;\n- `transcription/README.md`;\n- `transcription/parts/pdf-005-009.md`;\n- `transcription/parts/pdf-010-014.md`;\n- `transcription/parts/pdf-015-019.md`;\n- `transcription/parts/pdf-020-024.md`;\n- `transcription/parts/pdf-025-029.md`;\n- `transcription/parts/pdf-030-034.md`;\n- `transcription/parts/pdf-035-039.md`;\n- `transcription/parts/pdf-040-044.md`;\n- `transcription/parts/pdf-045-049.md`;\n- `transcription/parts/pdf-050-054.md`;\n- `transcription/parts/pdf-055-059.md`;\n- `transcription/parts/pdf-060-064.md`;\n- `transcription/parts/pdf-065-069.md`;\n- `notes/textual-notes-pdf-005-009.md`;\n- `notes/textual-notes-pdf-010-014.md`;\n- `notes/textual-notes-pdf-015-019.md`;\n- `notes/textual-notes-pdf-020-024.md`;\n- `notes/textual-notes-pdf-025-029.md`;\n- `notes/textual-notes-pdf-030-034.md`;\n- `notes/textual-notes-pdf-035-039.md`;\n- `notes/textual-notes-pdf-040-044.md`;\n- `notes/textual-notes-pdf-045-049.md`;\n- `notes/textual-notes-pdf-050-054.md`;\n- `notes/textual-notes-pdf-055-059.md`;\n- `notes/textual-notes-pdf-060-064.md`;\n- `notes/textual-notes-pdf-065-069.md`;\n- `notes/historical-glyph-audit.md`.\n''';s=s[:i]+files+s[j:]
s=re.sub(r'## Exact next activity\n\n> \*\*.*?\*\*\s*$',f'## Exact next activity\n\n> **{NEXT}**\n',s,count=1,flags=re.S);wr(p,s)
# Next prompt
wr('works/naam/NEXT_CHAT_PROMPT.md',f'''# Next Chat Prompt — நாம்\n\nContinue directly in `pugazg/kalaignar-cinema-works`, branch `main`, active work `works/naam/`.\n\n## LIVE MAIN IS AUTHORITATIVE\n\nFetch live `main` first and preserve newer durable work.\n\nCurrent durable checkpoint:\n\n- source intake / mapping: **complete / verified**;\n- canonical Tamil first pass: **PDF 5–69 / 65 of 67 pages**;\n- verified pages: **0**;\n- historical-glyph first-pass checked: **65/67**;\n- historical-glyph final verified: **0/67**;\n- open uncertainty markers: **2**;\n- final first-pass remainder: **PDF 70–71**.\n\n## Controlling source\n\nResolve `TVA_BOK_0064201_நாம்.pdf` before source-level visual work. Recorded identity: **72 PDF pages**, **115,948,588 bytes**, SHA-256 `0f7a54882eb6a5a8f83b29060c771ef18dee2b9e108c8797184de2b97c30b7ad`, image-only; screenplay PDF **5–71**.\n\n## Frozen first-pass batches PDF 5–69\n\nDo not redo or silently rewrite completed pages absent new direct-scan evidence. The cumulative source uncertainties remain exactly **2** (PDF 5 damaged introductory text; PDF 9 unclear montage word). PDF 10–69 adds none.\n\nPDF 69 ends mid-dialogue in `காட்சி-45` at `படித்தால் பாவம் என்று உன்`. PDF 70 must continue that same Kumaran source unit without duplication or invented completion.\n\nEnglish translation remains blocked until the canonical Tamil passes visual-fidelity and final historical-glyph verification.\n\n## Exact next activity\n\n> **{NEXT}**\n''')
# data/works
p='data/works.json';x=json.loads((R/p).read_text(encoding='utf-8'));n=next(q for q in x if q.get('id')=='naam');n.update(canonical_tamil_transcription='partial-first-pass-through-pdf-069',historical_glyph_audit='partial-first-pass-through-pdf-069',next_action=NEXT,canonical_tamil_first_pass_pages_completed=65,canonical_tamil_first_pass_pdf_range_completed='5-69',canonical_tamil_first_pass_current_through_pdf=69,canonical_tamil_draft_pages=65,canonical_tamil_verified_pages=0,canonical_tamil_review_pages=65,canonical_tamil_open_uncertainty_markers=2,canonical_tamil_current_batch_path='works/naam/transcription/parts/pdf-065-069.md',canonical_tamil_current_textual_notes_path='works/naam/notes/textual-notes-pdf-065-069.md',historical_glyph_pages_checked=65,historical_glyph_pages_verified=0,visual_fidelity_audit='not-started');wr(p,json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n')
# root README
p='README.md';s=(R/p).read_text(encoding='utf-8');blk=f'''## நாம் status\n\n`TVA_BOK_0064201_நாம்.pdf` is the **active cinema source**. Intake and the 45-scene structural map are complete; canonical Tamil first-pass transcription is in progress.\n\n- canonical Tamil first pass: **PDF 5–69 / 65 of 67 pages**;\n- verified pages: **0**; visual-fidelity audit: **not-started**;\n- historical-glyph first-pass checked: **65/67**; final glyph-verified: **0/67**;\n- open source uncertainty markers: **2**, both carried from PDF 5/9; PDF 10–69 adds none;\n- newest batch: `works/naam/transcription/parts/pdf-065-069.md`;\n- PDF 69 ends mid-Kumaran dialogue in scene 45; PDF 70 continues the same source unit;\n- downstream derivatives and English remain blocked pending verified Tamil.\n\n**Next:** {NEXT}\n''';s=section(s,'## நாம் status','## ராஜா ராணி status',blk);wr(p,s)
# master handover
p='docs/HANDOVER_KALAIGNAR_CINEMA_WORKS.md';s=(R/p).read_text(encoding='utf-8');s=re.sub(r'- \*\*Naam / நாம்\*\* — active work;.*?Source SHA-256 `0f7a54882eb6a5a8f83b29060c771ef18dee2b9e108c8797184de2b97c30b7ad`\.', '- **Naam / நாம்** — active work; intake/map complete; canonical Tamil first pass **PDF 5–69 / 65 of 67**; glyph first-pass **65/67**; verified **0/67**; 2 carried source uncertainties; final first-pass remainder PDF 70–71. Source SHA-256 `0f7a54882eb6a5a8f83b29060c771ef18dee2b9e108c8797184de2b97c30b7ad`.',s,count=1,flags=re.S);blk=f'''## 8. Naam active checkpoint\n\nWork: `works/naam/`  \nSource: `TVA_BOK_0064201_நாம்.pdf`\n\n- intake / whole-scan map: **complete / verified**;\n- canonical Tamil first pass: **PDF 5–69 / 65 of 67 pages**;\n- canonical verified pages: **0**; visual-fidelity audit: **not-started**;\n- historical-glyph first-pass checked / final verified: **65/67 / 0/67**;\n- open source uncertainties: **2**, both inherited from PDF 5/9;\n- current batch: `works/naam/transcription/parts/pdf-065-069.md`;\n- current source notes: `works/naam/notes/textual-notes-pdf-065-069.md`;\n- PDF 69 ends mid-Kumaran dialogue at `படித்தால் பாவம் என்று உன்`; PDF 70 continues the same source unit;\n- structured derivatives / English / reader remain blocked.\n\n**Exact next activity:** {NEXT}\n''';s=section(s,'## 8. Naam active checkpoint','## 9. Ammayappan closed checkpoint',blk);wr(p,s)
# status audit
p='docs/STATUS_CONSISTENCY_AUDIT.md';s=(R/p).read_text(encoding='utf-8').replace('Audit date: 2026-09-06','Audit date: 2026-09-08').replace('| Naam / நாம் | intake/map complete; first pass **PDF 5–64 / 60 of 67**, 0 verified','| Naam / நாம் | intake/map complete; first pass **PDF 5–69 / 65 of 67**, 0 verified');blk=f'''## Naam current checkpoint\n\n- source intake / structural mapping: **complete / verified**;\n- canonical Tamil first pass: **PDF 5–69 / 65 of 67 pages**;\n- verified pages / visual-fidelity passed: **0 / 0**;\n- historical-glyph first-pass checked / final verified: **65 / 0**;\n- open uncertainty markers: **2**, both carried from PDF 5/9;\n- current draft: `works/naam/transcription/parts/pdf-065-069.md`;\n- current source notes: `works/naam/notes/textual-notes-pdf-065-069.md`;\n- PDF 65–69 introduces no new explicit uncertainty and no new distinct song/lyric/performance structure;\n- PDF 69 ends mid-Kumaran dialogue at `படித்தால் பாவம் என்று உன்`; PDF 70 continues the same source unit;\n- downstream scene/dialogue/character/song/English layers remain blocked until verified Tamil.\n\n**Next production phase:** {NEXT}\n''';s=section(s,'## Naam current checkpoint','## Ammayappan current checkpoint',blk);s=re.sub(r'\*\*Naam / நாம்\*\* is the active production work with intake/map complete and canonical Tamil first pass at \*\*PDF 5–64 / 60 of 67 pages\*\*, \*\*0 verified pages\*\*, historical-glyph first-pass \*\*60/67\*\*, and \*\*2 carried source uncertainties\*\*\. The next batch is PDF 65–69\.', '**Naam / நாம்** is the active production work with intake/map complete and canonical Tamil first pass at **PDF 5–69 / 65 of 67 pages**, **0 verified pages**, historical-glyph first-pass **65/67**, and **2 carried source uncertainties**. The final first-pass remainder is PDF 70–71.',s,count=1);wr(p,s)
print('Synchronized:');[print('-',q) for q in changed]
